export const initialOrders = [
  {
    id: "FD-240621",
    createdAt: "Today, 09:42",
    updatedAt: "4 min ago",
    client: "Moe Thandar",
    clientPhone: "09 774 221 890",
    pickup: "Kabar Aye Market, Yankin",
    pickupContact: "Linn Fashion",
    pickupPhone: "09 790 331 482",
    destination: "Sanchaung Street, Sanchaung",
    receiver: "May Thu",
    receiverPhone: "09 420 882 144",
    product: "Clothing package",
    category: "Fashion",
    quantity: 1,
    fragile: false,
    note: "Call receiver before arrival.",
    status: "pending",
    paymentStatus: "pending_approval",
    paymentMethod: "Mobile banking",
    cod: 0,
    fee: 3000,
    riderId: null,
  },
  {
    id: "FD-240620",
    createdAt: "Today, 09:18",
    updatedAt: "12 min ago",
    client: "City Mart Express",
    clientPhone: "09 963 210 448",
    pickup: "City Mart, Hledan",
    pickupContact: "Counter 4",
    pickupPhone: "09 963 210 448",
    destination: "Insein Road, Kamayut",
    receiver: "Ko Aung",
    receiverPhone: "09 778 458 020",
    product: "Groceries",
    category: "Food",
    quantity: 3,
    fragile: false,
    note: "Keep bag upright.",
    status: "going_to_pickup",
    paymentStatus: "unpaid",
    paymentMethod: "Cash on delivery",
    cod: 18500,
    fee: 2500,
    riderId: "R-001",
  },
  {
    id: "FD-240619",
    createdAt: "Today, 08:56",
    updatedAt: "19 min ago",
    client: "Golden Petals",
    clientPhone: "09 421 118 779",
    pickup: "Baho Road, Ahlone",
    pickupContact: "Golden Petals",
    pickupPhone: "09 421 118 779",
    destination: "Pyay Road, Dagon",
    receiver: "Nandar",
    receiverPhone: "09 798 322 144",
    product: "Flower bouquet",
    category: "Gift",
    quantity: 1,
    fragile: true,
    note: "Handle with care.",
    status: "picked_up",
    paymentStatus: "paid",
    paymentMethod: "Prepaid",
    cod: 0,
    fee: 3500,
    riderId: "R-003",
  },
  {
    id: "FD-240618",
    createdAt: "Today, 08:41",
    updatedAt: "25 min ago",
    client: "Hnin Pharmacy",
    clientPhone: "09 540 716 551",
    pickup: "Myaynigone, Sanchaung",
    pickupContact: "Hnin Pharmacy",
    pickupPhone: "09 540 716 551",
    destination: "Bogyoke Road, Lanmadaw",
    receiver: "U Min Lwin",
    receiverPhone: "09 730 118 404",
    product: "Medicine package",
    category: "Health",
    quantity: 2,
    fragile: false,
    note: "Deliver before noon.",
    status: "delivered",
    paymentStatus: "paid",
    paymentMethod: "Cash",
    cod: 12000,
    fee: 3000,
    riderId: "R-002",
  },
];

export const initialRiders = [
  {
    id: "R-001",
    name: "Aung Kyaw",
    initials: "AK",
    phone: "09 772 883 120",
    status: "busy",
    activeOrders: 1,
    area: "Kamayut",
    lastSeen: "1 min ago",
    cashHeld: 18500,
    vehicle: "Motorbike",
  },
  {
    id: "R-002",
    name: "Min Thu",
    initials: "MT",
    phone: "09 452 319 805",
    status: "available",
    activeOrders: 0,
    area: "Lanmadaw",
    lastSeen: "2 min ago",
    cashHeld: 15000,
    vehicle: "Motorbike",
  },
  {
    id: "R-003",
    name: "Thiri Ko",
    initials: "TK",
    phone: "09 798 420 188",
    status: "busy",
    activeOrders: 1,
    area: "Dagon",
    lastSeen: "Just now",
    cashHeld: 0,
    vehicle: "Motorbike",
  },
  {
    id: "R-004",
    name: "Nyein Chan",
    initials: "NC",
    phone: "09 967 422 310",
    status: "available",
    activeOrders: 0,
    area: "Yankin",
    lastSeen: "3 min ago",
    cashHeld: 0,
    vehicle: "Motorbike",
  },
  {
    id: "R-005",
    name: "Zin Mar",
    initials: "ZM",
    phone: "09 420 103 922",
    status: "offline",
    activeOrders: 0,
    area: "Tamwe",
    lastSeen: "42 min ago",
    cashHeld: 8500,
    vehicle: "Motorbike",
  },
];

export const statusLabels = {
  pending: "Pending approval",
  approved: "Approved",
  rider_assigned: "Rider assigned",
  rider_accepted: "Accepted",
  going_to_pickup: "Going to pickup",
  arrived_at_pickup: "At pickup",
  picked_up: "Picked up",
  going_to_delivery: "Going to delivery",
  arrived_at_delivery: "At destination",
  delivered: "Delivered",
  completed: "Completed",
  failed: "Failed",
  cancelled: "Cancelled",
};

export const nextRiderActions = {
  rider_assigned: ["Accept assignment", "rider_accepted"],
  rider_accepted: ["Start pickup journey", "going_to_pickup"],
  going_to_pickup: ["Confirm pickup arrival", "arrived_at_pickup"],
  arrived_at_pickup: ["Confirm product pickup", "picked_up"],
  picked_up: ["Start delivery journey", "going_to_delivery"],
  going_to_delivery: ["Confirm destination arrival", "arrived_at_delivery"],
  arrived_at_delivery: ["Confirm delivered", "delivered"],
  delivered: ["Complete order", "completed"],
};
